---
language: python
python: "2.7"
before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq python-pip
install:
  - pip install ansible
script:
  - cd tests
  - ansible-playbook -i inventory test.yml
