---
# tasks file for nextcloud

- name: download nextcloud archive
  get_url:
    url: "{{ nextcloud_tarball_url }}"
    dest: "{{ nextcloud_tarball_tmp_path }}"
    checksum: 'md5:{{ nextcloud_tarball_md5_sum_url }}'

- name: handle dependencies
  include: dependencies.yml

- name: ensure install path exists
  file:
    path: "{{ nextcloud_install_path }}"
    state: directory
    user: "{{ nextcloud_system_user }}"
    group: "{{ nextcloud_system_group }}"

- name: unarchive tarball
  unarchive:
    src: "{{ nextcloud_tarball_tmp_path }}"
    dest: "{{ nextcloud_install_path }}"
    remote_src: yes
